version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs
      - ./env.yml:/config/env.yml:ro
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - mcp-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=test_database
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - mcp-network
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  mysql-data:
    driver: local

networks:
  mcp-network:
    driver: bridge 